[package]
name = "mpk-cracow-api"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7", features = ["serde"] }
reqwest = { version = "0.11", features = [ "gzip", "deflate", "json", "serde_json" ] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }